### ISSUE TITLE
Where do i get other files?

### ISSUE THREAD

**Issue by Cyber1000** [timschumi/lineage-build-archiver#2]
Hi, thanks for this project, I found a build for my discontinued Device: https://wiki.lineageos.org/devices/pdx206/install/
The problem here:  According to the decription I also need a dtbo.img,  vbmeta.img, recovery.img too. Where do I find these?

Thanks!

**Comment by Cyber1000** [comment]
ah found the solution: https://wiki.lineageos.org/extracting_blobs_from_zips#extracting-proprietary-blobs-from-payload-based-otas

This extracts the img-Files from the zip.

**Comment by timschumi** [comment]
Images are not archived directly because they are not listed in the updater API and because they don't have a verifiable signature. For A/B devices, many images can indeed be recovered from `payload.bin`. Other devices or images may require other steps.

I opened #3 for tracking the automation of this.
